apiVersion: paas.sogou.com/v1
kind: NginxVhost
metadata:
  name: rq-fsender
  namespace: search-databus
  labels:
    paas.sogou.com/app: rq-fsender
spec:
  domain: sender.databus.thanos.sogou
  path: /
  attributes:
    - key: "proxy_connect_timeout"
      value: "5s"
    - key: "proxy_read_timeout"
      value: "60s"
