apiVersion: v1
kind: Service
metadata:
  namespace: search-databus
  name: rq-fsender
  labels:
    paas.sogou.com/app: rq-fsender
spec:
  ports:
    - port: 6789
      name: http-port
  clusterIP: None
  selector:
    paas.sogou.com/app: rq-fsender