log:
  level: "debug"

http:
  port: "2021"
  api:
    path: "api"

db:
  mysql:
    host: "tcp(127.0.0.1:3306)"
    user: "root"
    password: "root"
    dbname: "fsender2"

upload:
  path: "./upload_files/"

task:
  concurrent: 10
